import type { NextPage } from 'next'
import Head from 'next/head'
import ContactUs from '../components/organisms/ContactUs'
import Extensions from '../components/organisms/Extensions'
import FAQ from '../components/organisms/FAQ'
import Features from '../components/organisms/Features'
import Footer from '../components/organisms/Footer'
import Hero from '../components/organisms/Hero'
import NavBar from '../components/organisms/NavBar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Terapia Mia | Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar/>
        <Hero/>
        <Features/>
        <Extensions/>
        <FAQ/>
        <ContactUs/>
        <Footer/>
      </main>

    </div>
  )
}

export default Home
